export default {
  en: [
    {key: "Recording browser information", value: "From time to time, information may be put on your computer to help us improve our website or improve our services to you. This information is commonly known as “cookies” which many websites are also currently using. “Cookies” are pieces of information stored on your computer’s hard disk or browser, not on a website. They allow to collect some information about your computer such as IP address, operating system, browser mode and addresses of related websites. If you do not wish to receive these cookies, or would like to be notified when these cookies are placed, you can set your browser to do this if your browser supports it. Please note, if you turn off receiving cookies, you will not be able to access or use certain features on the website that are not specified in advance. We are not intentionally restricting your use in this situation, this is only limited to programming and website building."},
    {key: "Information security", value: "When programming the website, we may put in place commercially reasonable laws to prevent illegal access and improper use of your personal information submitted to AMELA through use of this website. As there is always a risk involved in providing personal data, whether provided in person, by phone or over the internet, or through other technical means; and no technical system is absolutely safe or against all “hackers” and “tampers” (those who enter illegally to rummage through information), AMELA always strives to take appropriate precautions. appropriate for each characteristic of the information to prevent and minimize possible risks when you use this website."},
    {key: "Information by Email", value: "When you sign up for the service, the email address you provide will be used as a means of communication with you. First of all, please make sure that you provide an email address that is useful to you during the use of the service. We may send the necessary information via email or receive your support request. In case you no longer use the provided email, please notify us about this change. For your protection, AMELA may temporarily stop accepting requests via the email you provided if it notices unusual information – until we can contact you to confirm."},
    {key: "Adjustment information", value: "SkyLab will actively or at your request add, correct or delete personal information data that is inaccurate, incomplete or not up to date while you are still associated with our activities."},
    {key: "Off-site links", value: "This website may contain links to other websites placed for the purpose of introducing or supplementing relevant information for your reference. AMELA is not responsible for the content or behavior of any other website."},
    {key: "Changes of Rules", value: "SkyLab may change this policy from time to time, including adding, removing part of content or suspending the website without notice. However, if this policy is changed in a way that may be detrimental to you, AMELA will attempt to notify you of the change via the email or phone number you provided or on the homepage."},
  ],
  jp: [
    {key: "", value: "SKYLABは、ラボ型オフショア開発事業、システム開発事業を実施する上で、お客様の個人情報がプライバシーを構成する重要な情報であることを深く認識し、業務において個人情報を取り扱う場合には、個人情報に関する法令及び個人情報保護のために定めた社内規定を定め、また、組織体制を整備し、個人情報の適切な保護に努めることにより、お客様を尊重し、当社に対する期待と信頼に応えていきます。"},
    {key: "個人情報の取得、利用、提供", value: "当社は、事業活動の範囲内で個人情報の利用目的を特定し、その目的達成のために必要な限度で公正かつ適正に個人情報の取得、利用及び提供を行います。また、取得した個人情報の目的外利用をしないよう処置を講じます。"},
    {key: "法令・規範の遵守", value: "当社は、個人情報に関する法令、国が定める指針、その他の規範及び社会秩序を遵守し、個人情報の適切な保護に努めます。"},
    {key: "個人情報の適切な管理", value: "当社は、私たちが取り扱う個人情報について、不正アクセス、紛失、破壊、改ざん、漏えいなどの危険を十分に認識し、合理的な安全対策を実施するとともに、問題が発生した場合は適切な是正措置を講じます。"},
    {key: "問い合わせへの対応", value: "当社は、私たちが取り扱う個人情報について、本人から開示、訂正、利用停止及び苦情相談等のお問い合わせがあった場合は適正に対応します。"},
    {key: "継続的改善", value: "当社は、個人情報保護に関する管理規定及び管理体制を整備し、全社員で徹底して運用するとともに定期的な見直しを行い、個人情報保護マネジメントシステムの継続的な改善に努めます。"},
    {key: "問い合わせ窓口", value: "窓口の名称　：　SkyLab VietNam<br>連絡先住所　：　Ha Noi, Cau Giay, Dich Vong Hau Guard, 19 Duy Tan Street, Zodiac Building 10F<br>電子メール　：　info@skylab.vn"},
  ],
  vi: [
    {key: "Recording browser information", value: "From time to time, information may be put on your computer to help us improve our website or improve our services to you. This information is commonly known as “cookies” which many websites are also currently using. “Cookies” are pieces of information stored on your computer’s hard disk or browser, not on a website. They allow to collect some information about your computer such as IP address, operating system, browser mode and addresses of related websites. If you do not wish to receive these cookies, or would like to be notified when these cookies are placed, you can set your browser to do this if your browser supports it. Please note, if you turn off receiving cookies, you will not be able to access or use certain features on the website that are not specified in advance. We are not intentionally restricting your use in this situation, this is only limited to programming and website building."},
    {key: "Information security", value: "When programming the website, we may put in place commercially reasonable laws to prevent illegal access and improper use of your personal information submitted to AMELA through use of this website. As there is always a risk involved in providing personal data, whether provided in person, by phone or over the internet, or through other technical means; and no technical system is absolutely safe or against all “hackers” and “tampers” (those who enter illegally to rummage through information), AMELA always strives to take appropriate precautions. appropriate for each characteristic of the information to prevent and minimize possible risks when you use this website."},
    {key: "Information by Email", value: "When you sign up for the service, the email address you provide will be used as a means of communication with you. First of all, please make sure that you provide an email address that is useful to you during the use of the service. We may send the necessary information via email or receive your support request. In case you no longer use the provided email, please notify us about this change. For your protection, AMELA may temporarily stop accepting requests via the email you provided if it notices unusual information – until we can contact you to confirm."},
    {key: "Adjustment information", value: "SkyLab will actively or at your request add, correct or delete personal information data that is inaccurate, incomplete or not up to date while you are still associated with our activities."},
    {key: "Off-site links", value: "This website may contain links to other websites placed for the purpose of introducing or supplementing relevant information for your reference. AMELA is not responsible for the content or behavior of any other website."},
    {key: "Changes of Rules", value: "SkyLab may change this policy from time to time, including adding, removing part of content or suspending the website without notice. However, if this policy is changed in a way that may be detrimental to you, AMELA will attempt to notify you of the change via the email or phone number you provided or on the homepage."},
  ],
}